FROM digrouz/alpine-s6:latest

ARG SQUID_VERSION=''

LABEL maintainer="DI GREGORIO Nicolas <nicolas.digregorio@gmail.com>"

### Environment variables
ENV SQUID_VERSION="${SQUID_VERSION}" 

# Copy config files
COPY root/ /

### Install Application
RUN set -x && \
    apk --no-cache upgrade && \
    apk add --no-cache --virtual=run-deps \
      squid=${SQUID_VERSION} \
    && \
    rm -rf /tmp/* \
           /var/cache/apk/*  \
           /var/tmp/*

### Volume
VOLUME ["/data"]

### Expose ports
EXPOSE 3128
